# Generated by Django 5.1.3 on 2024-11-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('contact_number', models.IntegerField()),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('partner', 'Partner'), ('admin', 'Admin')], max_length=30)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
